Add number of workers to scale up REST API
road-core/service pull request #70
Opened 2024-10-22 13:12 UTC by r0x0d

This patch introduces the ability to increase the number of workers for the REST API via its configuration file.

## Description

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)
- [ ] CI configuration change
- [ ] Konflux configuration change

## Related Tickets & Documents

- Related Issue #
- Closes #51

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

2024-10-22 13:12 UTC, r0x0d commented
@tisnik probably this still needs some stuff to be finished. I was not sure where the documentation should go, so I found a `config.puml` in the docs folder. Let me know if there is more to be done here and where I should go to finish the task.

2024-10-22 18:41 UTC, tisnik requested changes
it looks ok, I'd just suggest to remove the "optionality" of this attribute (if pydantic allow it)

2024-10-22 18:41 UTC, tisnik commented on ols/app/models/config.py
> +    max_workers: Optional[int] = 1
from lines 934 and 960 it seems it is not `Optional`, just `int`

2024-10-23 15:16 UTC, tisnik approved these changes
it looks good!

2024-10-23 15:16 UTC, merged